import TanstackProvider from "@/share/providers/TanstackProvider";
import { Inter, Lato } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanstackProvider>
        <body
          className={`bg-backgroundPage ${lato.className} dark:bg-backgroundPageDark`}
        >
          {children}
        </body>
      </TanstackProvider>
    </html>
  );
}
